import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e6eeff',
        'surface-container-high': '#dee9fc',
        'surface-container-highest': '#d9e3f6',
        'surface': '#f8f9ff',
        'surface-bright': '#f8f9ff',
        'surface-dim': '#d0dbed',
        'surface-variant': '#d9e3f6',
        'surface-tint': '#465f88',
        'on-surface': '#121c2a',
        'on-surface-variant': '#44474e',
        'inverse-surface': '#27313f',
        'inverse-on-surface': '#eaf1ff',
        'outline': '#74777f',
        'outline-variant': '#c4c6cf',
        'primary': '#000a1e',
        'on-primary': '#ffffff',
        'primary-container': '#002147',
        'on-primary-container': '#708ab5',
        'inverse-primary': '#aec7f6',
        'primary-fixed': '#d6e3ff',
        'primary-fixed-dim': '#aec7f6',
        'on-primary-fixed': '#001b3d',
        'on-primary-fixed-variant': '#2d476f',
        'secondary': '#705d00',
        'on-secondary': '#ffffff',
        'secondary-container': '#fcd400',
        'on-secondary-container': '#6e5c00',
        'secondary-fixed': '#ffe16d',
        'secondary-fixed-dim': '#e9c400',
        'on-secondary-fixed': '#221b00',
        'on-secondary-fixed-variant': '#544600',
        'tertiary': '#080b0e',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#1f2225',
        'on-tertiary-container': '#86898d',
        'tertiary-fixed': '#e0e2e6',
        'tertiary-fixed-dim': '#c4c7ca',
        'on-tertiary-fixed': '#191c1f',
        'on-tertiary-fixed-variant': '#44474a',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'background': '#f8f9ff',
        'on-background': '#121c2a',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'gutter': '32px',
        'stack-lg': '64px',
        'stack-md': '32px',
        'stack-sm': '16px',
        'base': '8px',
        'margin-mobile': '20px',
      },
      fontFamily: {
        'h1': ['Inter', 'sans-serif'],
        'h2': ['Inter', 'sans-serif'],
        'h3': ['Inter', 'sans-serif'],
        'body-lg': ['Newsreader', 'serif'],
        'body-md': ['Newsreader', 'serif'],
        'body-sm': ['Newsreader', 'serif'],
        'label-caps': ['Inter', 'sans-serif'],
        'button': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'h1': ['48px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '700' }],
        'h2': ['36px', { lineHeight: '1.25', letterSpacing: '-0.01em', fontWeight: '600' }],
        'h3': ['28px', { lineHeight: '1.3', fontWeight: '600' }],
        'body-lg': ['20px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-sm': ['16px', { lineHeight: '1.5', fontWeight: '400' }],
        'label-caps': ['14px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
        'button': ['16px', { lineHeight: '1', fontWeight: '600' }],
      },
      maxWidth: {
        'container': '1280px',
      },
    },
  },
  plugins: [],
}

export default config
